### ISSUE TITLE
After 1 hour of installation phase, unable to run on windows.

### ISSUE THREAD

**Issue by JordanMicahBennett** [koriavinash1/DeepBrainSeg#11]
After running through a long cycle of installation on my Windows 10 machine, including trying either torch cpu or gpu, I finally got rid of all installation errors, apparently.

Afterward, upon invoking DeepBrainSegUI.py, via python 3, I get the following error:

![image](https://user-images.githubusercontent.com/3666405/87259801-8206fa80-c473-11ea-93bd-c88045c7f5b7.png)

Is it possible to state precisely what version of the main modules you use pertaining to this repository/pypi distribution?

**Despite having the latest pip installed, which is said to automatically install required versions, I am not sure that is the case here.

**Comment by JordanMicahBennett** [comment]
I am closing this issue.
I managed to set this up on windows after a week of somewhat struggling:

https://github.com/JordanMicahBennett/DeepBrainSeg/blob/master/WINDOWS%2010%20INSTALLATION%20GUIDE.md

![image](https://github.com/JordanMicahBennett/DeepBrainSeg/blob/master/DeepBrainSegUI-running-on-Windows-10.gif)
Figure: DeepBrainSeg on Windows 10.

**Comment by koriavinash1** [comment]
Glad that you were able to fix this issue, thanks for updating the readme.

**Comment by JordanMicahBennett** [comment]
> Glad that you were able to fix this issue, thanks for updating the readme.

Thanks for your hard work on DeepBrainSeg. I know neither you nor your gpus had it easy!
